# Generated by Django 2.0.2 on 2018-03-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180306_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后端开发', max_length=100, verbose_name='课程类型'),
        ),
    ]
