# Generated by Django 2.0.2 on 2018-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='python', max_length=100, verbose_name='课程标签'),
        ),
    ]
