# Generated by Django 2.0.2 on 2018-03-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courseresource_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresource',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='视频链接'),
        ),
    ]
