# Generated by Django 2.0.2 on 2018-03-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180306_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_kown',
            field=models.CharField(default='', max_length=100, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='will_learn',
            field=models.CharField(default='', max_length=100, verbose_name='老师告诉你'),
        ),
    ]
