# Generated by Django 2.0.2 on 2018-03-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='need_kown',
            new_name='need_know',
        ),
    ]
