# Generated by Django 2.0.2 on 2018-03-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180301_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('modify_email', '修改邮箱')], max_length=30, verbose_name='验证码类型'),
        ),
    ]
