# Generated by Django 2.0.2 on 2018-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='address',
            field=models.CharField(default='北京', max_length=150, verbose_name='机构地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='organizations/%Y/%m', verbose_name='logo'),
        ),
    ]
