# Generated by Django 2.0.2 on 2018-03-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20180304_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='organizations/%Y/%m', verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/%Y/%m', verbose_name='头像'),
        ),
    ]
