# Generated by Django 2.0.2 on 2018-03-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20180305_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='work_positon',
            new_name='work_position',
        ),
    ]
