# Generated by Django 2.0.2 on 2018-03-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20180309_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='知名高校', max_length=10, verbose_name='机构标签'),
        ),
    ]
